# Generated by Django 4.0 on 2021-12-10 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_title', models.CharField(blank=True, max_length=200, null=True)),
                ('post_description', models.TextField(blank=True, null=True)),
                ('post_published', models.DateTimeField(auto_now_add=True)),
                ('post_updated', models.DateTimeField(auto_now=True)),
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_tags', models.ManyToManyField(to='post.Tag')),
            ],
        ),
    ]
